dataset:
  3d_covariates:
  - t
  - w
  - rh
  - so2
  - ql
  groundtruth: so4_mass_conc
  path: data/sulfates/final_dataset_lat_321_lon_321_t_6_01_2007.nc
  target: so4cmass
  to_log_domain:
  - t
  trimming_altitude_idx: 0
evaluation:
  slice_latitude_idx: 70
  slice_time_idx: 0
  slices_covariates:
  - t
  - w
  - rh
  - so2
  - so4
  - ql
model:
  alpha: 2.5e-05
  fit_intercept: true
  transform: square
training:
  lr: 0.0001
  n_epochs: 500
