################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH VARIATIONAL CMP
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/south_pac_lat_321_lon_321_lev_72_t_6_sulfates.nc

  # Path to air density file
  air_density_file_path: data/air_density_sp.nc

  # Altitude index below which data is dropped
  trimming_altitude_idx: 25

  # Variable for which a logdomain version is created names log_<variable_name> - does not override original variable
  to_log_domain:
    - rh
    - co
    - so4
    - cocl
    - totexttau
    - suexttau
    - so4smass
    - suscatau

  # Variables to use as 3D covariates
  3d_covariates:
    - t
    - w
    - delp
    - log_rh
    - log_co
    - log_so4

  # Variables to use as 2D covariates
  2d_covariates:
    - ps
    - log_cocl
    - log_totexttau
    - log_suexttau
    - log_so4smass
    - log_suscatau


  # Variable to use as 2D aggregate target
  target: so4cmass

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: so4_mass_conc



# MODEL SPECIFICATIONS
model:
  # Number of inducing points to use
  n_inducing_points: 211

  # Transformation to apply
  transform: 'linear'

  # Inverse regularization parameter for CME estimation
  lbda: 0.01


# TRAINING SPECS
training:
  # Batch size
  batch_size: 128

  # Batch size used for CMO estimation
  batch_size_xy: 400

  # Number of training epochs
  n_epochs: 100

  # Learning rate
  lr: 0.1

  # Beta weighthing of KL term in ELBO
  beta: 1e-3


# EVALUATION
evaluation:
  # Size of chunks used to scale inference of posterior mean
  chunk_size: 500

  # Latitude index of slice to plot
  slice_latitude_idx: 50

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - rh
    - t
    - w
    - delp
    - co
    - so4
