################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH VARIATIONAL CMP
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/south_pac_lat_321_lon_321_lev_72_t_6_sulfates.nc

  # Path to air density file
  air_density_file_path: data/air_density_sp.nc

  # Altitude index below which data is dropped
  trimming_altitude_idx: 25

  # Variable for which a logdomain version is created names log_<variable_name> - does not override original variable
  to_log_domain:
    - rh
    - co
    - so4
    - cocl
    - totexttau
    - suexttau
    - so4smass
    - suscatau

  # Variables to use as 3D covariates
  3d_covariates:
    - t
    - w
    - delp
    - log_rh
    - log_co
    - log_so4

  # Variables to use as 2D covariates
  2d_covariates:
    - ps
    - log_cocl
    - log_totexttau
    - log_suexttau
    - log_so4smass
    - log_suscatau


  # Variable to use as 2D aggregate target
  target: so4cmass

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: so4_mass_conc
