################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH VARIATIONAL CMP
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/sulfates/south_pac_lat_321_lon_321_t_6_sulfates_final.nc

  # Altitude index below which data is dropped
  trimming_altitude_idx: 25

  # Variable for which a logdomain version is created names log_<variable_name> - does not override original variable
  to_log_domain:
    - rh
    - so2
    - dmsmass
    - so2cmass
    - so2smass
    - tox
    - lwp

  # Variables to use as 3D covariates
  3d_covariates:
    - t
    - w
    - log_rh
    - log_so2

  # Variables to use as 2D covariates
  2d_covariates:
    - tlml
    - pblh
    - log_dmsmass
    - log_so2cmass
    - log_so2smass
    - log_tox
    - log_lwp


  # Variable to use as 2D aggregate target
  target: so4cmass

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: so4_mass_conc



# MODEL SPECIFICATIONS
model:
  # Number of inducing points to use
  n_inducing_points: 211

  # Transformation to apply
  transform: 'linear'

  # Inverse regularization parameter for CME estimation
  lbda: 0.01


# TRAINING SPECS
training:
  # Batch size
  batch_size: 2048

  # Batch size used for CMO estimation
  batch_size_xy: 400

  # Number of training epochs
  n_epochs: 100

  # Learning rate
  lr: 0.1

  # Beta weighthing of KL term in ELBO
  beta: 1


# EVALUATION
evaluation:
  # Size of chunks used to scale inference of posterior mean
  chunk_size: 2048

  # Latitude index of slice to plot
  slice_latitude_idx: 50

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - t
    - w
    - rh
    - so2
