################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH TWO STAGED WARPED AGGREGATE RIDGE REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: /data/ziz/not-backed-up/scratch/bouabid/sulfates/final_dataset_lat_321_lon_321_t_6_01_2007.nc

  # Altitude index below which data is dropped
  trimming_altitude_idx: 0

  # Variable for which a logdomain version is created names log_<variable_name> - does not override original variable
  to_log_domain:
    - t

  # Variables to use as 2D covariates
  2d_covariates:
    - so4cmass
    - lwp


  # Variables to use as 3D covariates
  3d_covariates:
    - t
    - w
    - rh
    - so2
    - ql

  # Variable to use as 2D aggregate target
  target: so4cmass

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: so4_mass_conc


# MODEL SPECIFICATIONS
model:
  # L2 regularization weight for stage 1
  alpha_2d: 0.01

  # L2 regularization weight for stage 2
  alpha_3d: 100000000000

  # Whether to use bias or not in stage 1
  fit_intercept_2d: True

  # Whether to use bias or not in stage 1
  fit_intercept_3d: True

  # Warping transformation
  transform: 'square'


# TRAINING
training:
  # Number of training epochs
  n_epochs: 4000

  # Learning rate
  lr: 0.0001


# EVALUATION
evaluation:
  # Latitude index of slice to plot
  slice_latitude_idx: 100

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - t
    - w
    - rh
    - so2
    - so4
    - ql
