################################################################################
#   CONFIGURATIONS FOR VERTICAL DISAGGREGATION EXPERIMENT WITH AGGREGATE RIDGE REGRESSION
################################################################################

# DATASET
dataset:
  # Path to main model data .nc file
  path: data/south_pac_lat_321_lon_321_lev_72_t_6_sulfates.nc

  # Path to air density file
  air_density_file_path: data/air_density_sp.nc

  # Altitude index below which data is dropped
  trimming_altitude_idx: 25

  # Variable for which a logdomain version is created names log_<variable_name> - does not override original variable
  to_log_domain:
    - totexttau
    - totscatau
    - cocl
    - suexttau
    - so4smass
    - suscatau
    - rh
    - co
    - so4
    - so4cmass
    - so4_mass_conc

  # Variables to use as 3D covariates
  3d_covariates:
    - log_rh
    - t
    - w
    - delp
    - log_co
    - log_so4

  # Variable to use as 2D aggregate target
  target: so4cmass

  # Variable corresponding to unobserved groundtruth 3D field
  groundtruth: so4_mass_conc




# MODEL SPECIFICATIONS
model:
  # L2 regularization weight
  alpha: 0.001

  # Whether to use bias or not
  fit_intercept: True

  # Warping transformation
  transform: 'smooth_abs'




# TRAINING
training:
  # Number of training epochs
  n_epochs: 1000

  # Learning rate
  lr: 0.1



# EVALUATION
evaluation:
  # Latitude index of slice to plot
  slice_latitude_idx: 50

  # Time index of slice to plot
  slice_time_idx: 0

  # List of variables slices to plot
  slices_covariates:
    - rh
    - t
    - w
    - delp
    - co
    - so4
